@base_url = http://localhost:4000/api

# @name create_user
POST {{base_url}}
Content-Type: application/json

{
	"name": "Cebolinha",
	"email": "cebolinha@mail.com",
	"password": "Senha@123",
	"age": 23,
	"cpf": "11111111111",
	"cep": "12345678",
	"address": "Rua do Limoeiro"
}

###

# @name get_user
GET {{base_url}}/52aec1d0-87e2-432b-a99f-98898ad094ba

###

# @name delete_user
DELETE {{base_url}}/f37a3eb4-e968-4fb1-b09b-6d2183b86bf6